CREATE DATABASE IF NOT EXISTS vetcare
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE vetcare;

CREATE TABLE IF NOT EXISTS app_store (
  store_key VARCHAR(64) PRIMARY KEY,
  value_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
